### ISSUE TITLE
Failed to activate the autocomplete-latex-references package

### ISSUE THREAD

**Issue by PRemmen** [hesstobi/atom-autocomplete-latex-references#10]
The package does not work with latest update of Atom, see trace below. This error is thrown on every start up. Any solution for that? :)

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Windows 10
**Thrown From**: [autocomplete-latex-references](https://github.com/hesstobi/atom-autocomplete-latex-references) package 0.3.1

### Stack Trace

Failed to activate the autocomplete-latex-references package

```
At Cannot read property '1' of null

TypeError: Cannot read property '1' of null
    at module.exports (/packages/autocomplete-latex-references/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:61:29)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:82:25)
    at /packages/autocomplete-latex-references/node_modules/promisify-node/index.js:137:23
    at Array.forEach (<anonymous>)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:132:6)
    at module.exports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:164:10)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:4:6)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:1:1)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:16)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:1)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at Object.provide (/packages/autocomplete-latex-references/lib/main.coffee:64:27)
    at Package.activateServices (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3544442)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3541484)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1208969)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381902)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381864)
```

### Commands

```
     -0:58.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-python-debugger 0.3.4 
autocomplete-latex-cite 0.3.2 
autocomplete-latex-references 0.3.1 
autocomplete-python 1.14.1 
busy-signal 2.0.1 
convert-to-utf8 0.2.4 
file-icons 2.1.33 
highlight-selected 0.16.0 
intentions 1.1.5 
language-latex 1.2.0 
language-mako 0.6.0 
language-markdown 0.37.0 
language-modelica 0.5.1 
latex 0.50.2 
latex-autocomplete 1.1.1 
linter 2.3.0 
linter-flake8 2.4.0 
linter-htmlhint 1.6.2 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
preview-inline 1.5.1 
python-black 0.7.0 
split-diff 1.6.0 
symbols-tree-view 0.14.0 
wordcount 3.1.0 
```

**Comment by EnochMakenp** [comment]
I confirm the issue that seems to be different from #18: I originally had the two issues (the one reported in #18 and here) popping in the console at the start of Atom, I thought they had the same origin, thus I manually applied the fix for #18 from @mayhewsw and installed the new latex-to-unicode manually, and unfortunately now only this issue is popping up :-(
I've installed Atom 1.39.1 just a few days ago, and I'm on Windows 10.

**Comment by EnochMakenp** [comment]
This issue is a duplicate of #9

**Comment by PRemmen** [comment]
sorry for duplication. I'll close this issue, but I'm still looking forward to a solution :)
